version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  postgres_highload:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=highload
    container_name: postgres_highload
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    command: postgres -N 1000

  mysql_highload:
    image: mysql:8
    ports:
      - "3311:3306"
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql

  tarantool:
    image: tarantool/tarantool:3
    ports:
      - "3301:3301"
